name: Build

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v31

      - uses: cachix/cachix-action@v16
        with:
          name: soywod
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build frontend
        run: nix develop --command cargo leptos build --release

      - name: Build static server binary
        run: nix build

      - name: Package release
        run: |
          mkdir -p release
          cp result/bin/bilbo release/
          cp -r target/site release/
          tar czf bilbo-release.tar.gz -C release .

      - uses: actions/upload-artifact@v4
        with:
          name: bilbo-release
          path: bilbo-release.tar.gz
